#! /usr/bin/env python

import os, sys, subprocess
import eyed3

# preserve file modification times ?
preserve_mtime = True

# only accept mp3 files as m4a do not use id3 tags
filelist = sys.argv[1:]
for f in filelist:
   if not f.endswith('.mp3'):
      print "Use with mp3 files only"
      sys.exit(1)

# aacgain supports mp3 and m4a with AAC-LC (no Apple Lossless / ALAC)
cmd = ["aacgain", "-o", "-s", "s", "-q"] + filelist
pipe = subprocess.Popen(cmd, stdout=subprocess.PIPE).stdout

# skip first line of output (header)
pipe.next()

# parse output
trackinfo = []
for line in pipe:
   parts = line.rstrip("\n").split("\t")
   if parts[0] == '"Album"':
      albumframes = {
            u"replaygain_album_gain": u"%.2f dB" % (float(parts[2])),
            u"replaygain_album_peak": u"%.6f"    % (float(parts[3])/32768.),
         }
   else:
      trackinfo.append(parts)

# write replay gain frames to files
for entry in trackinfo:
   filename = entry[0]
   if preserve_mtime:
      stat = os.stat(filename)
   # detect file error
   if len(entry) == 1:
      print filename
      continue
   trackframes = {
      u"replaygain_track_gain": u"%.2f dB" % (float( entry[2])),
      u"replaygain_track_peak": u"%.6f"    % (float( entry[3])/32768.),
   }
   if len(trackinfo) > 1:
      trackframes.update(albumframes)
   mp3file = eyed3.load(filename)
   for key, value in trackframes.iteritems():
      mp3file.tag.user_text_frames.set(text=value,description=key)
   mp3file.tag.save(preserve_file_time=preserve_mtime)
