#!/bin/sh

DEBUG=1
nhttpd () {
    ss -nt state established '( sport = :8000 )' | tail -n+2 | wc -l
}

nctrl () {
    N=`ss -nt state established '( sport = :6600 )' | tail -n+2 | wc -l`
    V=`ss -nt state established '( dport = :6600 )' | tail -n+2 | grep -v mpd_dynamic | wc -l`
    echo $(($N-$V))
}

NCONN=-1
while true; do
    NH=`nhttpd`
    [ $DEBUG -eq 1 -a $NCONN -ne $NH ] && echo "$NH active httpd connections"
    if mpc | grep -q '^\[playing\]'; then
        curstate=1
    else
        curstate=0
    fi
    if [ $NH -eq 0 -a $curstate -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "No httpd connection and running"
        if [ `nctrl` -eq 0 ]; then
            [ $DEBUG -eq 1 ] && echo "No control connection, pausing"
            mpc -q pause
        fi
    elif [ $NH -ne 0 -a $curstate -eq 0 ]; then
        [ $DEBUG -eq 1 ] && echo "httpd connection, starting playback"
        mpc -q play
    fi
    NCONN=$NH
    sleep 5
done
